/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LoanPackage;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

/**
 *
 * @author Louis Valencia
 */
public class LoansApplication extends javax.swing.JFrame {

    /**
     * Creates new form LoansApplication
     */
    public LoansApplication() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PANE = new javax.swing.JTabbedPane();
        MAIN_PANE = new javax.swing.JPanel();
        LOAN_APPLICATION_BUTTON = new javax.swing.JToggleButton();
        LOAN_LIST_BUTTON = new javax.swing.JToggleButton();
        SEARCH_LOAN_BUTTON = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        LOANAPPLICATION_PANE = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        APPLICANTNAME_FIELD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        LOANAMOUNT_FIELD = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TERM_SELECTION = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        LOANTYPE_SELECTION = new javax.swing.JComboBox<>();
        SUBMIT_APPLICATION_BUTTON = new javax.swing.JButton();
        LOAN_APPLICATION_BACK_BUTTON = new javax.swing.JButton();
        DISPLAYLOAN_PANE = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DISPLAY_LOAN_TABLE = new javax.swing.JTable();
        DISPLAY_LOAN_BACK_BUTTON = new javax.swing.JButton();
        SEARCHLOAN_PANE = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        LOAN_NUMBER_FIELD = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        SEARCH_LOAN_TABLE = new javax.swing.JTable();
        SEARCH_LOAN_BACK_BUTTON = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LOAN_APPLICATION_BUTTON.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        LOAN_APPLICATION_BUTTON.setText("LOAN APPLICATION");
        LOAN_APPLICATION_BUTTON.setBorderPainted(false);
        LOAN_APPLICATION_BUTTON.setFocusPainted(false);
        LOAN_APPLICATION_BUTTON.setRolloverEnabled(false);
        LOAN_APPLICATION_BUTTON.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOAN_APPLICATION_BUTTONMouseClicked(evt);
            }
        });
        LOAN_APPLICATION_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOAN_APPLICATION_BUTTONActionPerformed(evt);
            }
        });

        LOAN_LIST_BUTTON.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        LOAN_LIST_BUTTON.setText("LOAN LIST");
        LOAN_LIST_BUTTON.setBorderPainted(false);
        LOAN_LIST_BUTTON.setFocusPainted(false);
        LOAN_LIST_BUTTON.setRolloverEnabled(false);
        LOAN_LIST_BUTTON.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOAN_LIST_BUTTONMouseClicked(evt);
            }
        });
        LOAN_LIST_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOAN_LIST_BUTTONActionPerformed(evt);
            }
        });

        SEARCH_LOAN_BUTTON.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        SEARCH_LOAN_BUTTON.setText("SEARCH LOAN");
        SEARCH_LOAN_BUTTON.setBorderPainted(false);
        SEARCH_LOAN_BUTTON.setFocusPainted(false);
        SEARCH_LOAN_BUTTON.setRolloverEnabled(false);
        SEARCH_LOAN_BUTTON.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SEARCH_LOAN_BUTTONMouseClicked(evt);
            }
        });
        SEARCH_LOAN_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCH_LOAN_BUTTONActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("KOMPANYA NI PERCY CO.");

        javax.swing.GroupLayout MAIN_PANELayout = new javax.swing.GroupLayout(MAIN_PANE);
        MAIN_PANE.setLayout(MAIN_PANELayout);
        MAIN_PANELayout.setHorizontalGroup(
            MAIN_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MAIN_PANELayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(MAIN_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LOAN_APPLICATION_BUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LOAN_LIST_BUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SEARCH_LOAN_BUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        MAIN_PANELayout.setVerticalGroup(
            MAIN_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MAIN_PANELayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(LOAN_APPLICATION_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LOAN_LIST_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SEARCH_LOAN_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        PANE.addTab("MAIN", MAIN_PANE);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Applicant Name:");

        APPLICANTNAME_FIELD.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        APPLICANTNAME_FIELD.setToolTipText("");
        APPLICANTNAME_FIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                APPLICANTNAME_FIELDActionPerformed(evt);
            }
        });
        APPLICANTNAME_FIELD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                APPLICANTNAME_FIELDKeyPressed(evt);
            }
        });

        jLabel3.setText("Loan Amount:");

        LOANAMOUNT_FIELD.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        LOANAMOUNT_FIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOANAMOUNT_FIELDActionPerformed(evt);
            }
        });

        jLabel4.setText("Term:");

        TERM_SELECTION.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Short ", "Medium ", "Long ", " " }));
        TERM_SELECTION.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TERM_SELECTION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TERM_SELECTIONActionPerformed(evt);
            }
        });

        jLabel5.setText("Loan Type:");

        LOANTYPE_SELECTION.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Business", "Personal" }));

        SUBMIT_APPLICATION_BUTTON.setText("Submit Application");
        SUBMIT_APPLICATION_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUBMIT_APPLICATION_BUTTONActionPerformed(evt);
            }
        });

        LOAN_APPLICATION_BACK_BUTTON.setText("Back");
        LOAN_APPLICATION_BACK_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOAN_APPLICATION_BACK_BUTTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LOANAPPLICATION_PANELayout = new javax.swing.GroupLayout(LOANAPPLICATION_PANE);
        LOANAPPLICATION_PANE.setLayout(LOANAPPLICATION_PANELayout);
        LOANAPPLICATION_PANELayout.setHorizontalGroup(
            LOANAPPLICATION_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LOANAPPLICATION_PANELayout.createSequentialGroup()
                .addGroup(LOANAPPLICATION_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LOANAPPLICATION_PANELayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(LOANAPPLICATION_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LOANAPPLICATION_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(32, 32, 32)
                        .addGroup(LOANAPPLICATION_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LOANTYPE_SELECTION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TERM_SELECTION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(APPLICANTNAME_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LOANAMOUNT_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(LOANAPPLICATION_PANELayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LOAN_APPLICATION_BACK_BUTTON))
                    .addGroup(LOANAPPLICATION_PANELayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(SUBMIT_APPLICATION_BUTTON)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        LOANAPPLICATION_PANELayout.setVerticalGroup(
            LOANAPPLICATION_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LOANAPPLICATION_PANELayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(LOAN_APPLICATION_BACK_BUTTON)
                .addGap(18, 18, 18)
                .addGroup(LOANAPPLICATION_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(APPLICANTNAME_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LOANAPPLICATION_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(LOANAMOUNT_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LOANAPPLICATION_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TERM_SELECTION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(21, 21, 21)
                .addGroup(LOANAPPLICATION_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LOANTYPE_SELECTION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(SUBMIT_APPLICATION_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        TERM_SELECTION.getAccessibleContext().setAccessibleName("");

        PANE.addTab("LOAN APPLICATION", LOANAPPLICATION_PANE);

        DISPLAY_LOAN_TABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Loan Amount", "Term", "Loan type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DISPLAY_LOAN_TABLE.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(DISPLAY_LOAN_TABLE);
        if (DISPLAY_LOAN_TABLE.getColumnModel().getColumnCount() > 0) {
            DISPLAY_LOAN_TABLE.getColumnModel().getColumn(0).setResizable(false);
            DISPLAY_LOAN_TABLE.getColumnModel().getColumn(1).setResizable(false);
            DISPLAY_LOAN_TABLE.getColumnModel().getColumn(2).setResizable(false);
            DISPLAY_LOAN_TABLE.getColumnModel().getColumn(3).setResizable(false);
        }

        DISPLAY_LOAN_BACK_BUTTON.setText("Back");
        DISPLAY_LOAN_BACK_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DISPLAY_LOAN_BACK_BUTTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DISPLAYLOAN_PANELayout = new javax.swing.GroupLayout(DISPLAYLOAN_PANE);
        DISPLAYLOAN_PANE.setLayout(DISPLAYLOAN_PANELayout);
        DISPLAYLOAN_PANELayout.setHorizontalGroup(
            DISPLAYLOAN_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DISPLAYLOAN_PANELayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(DISPLAYLOAN_PANELayout.createSequentialGroup()
                .addGroup(DISPLAYLOAN_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DISPLAYLOAN_PANELayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel6))
                    .addGroup(DISPLAYLOAN_PANELayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(DISPLAY_LOAN_BACK_BUTTON)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DISPLAYLOAN_PANELayout.setVerticalGroup(
            DISPLAYLOAN_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DISPLAYLOAN_PANELayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(DISPLAY_LOAN_BACK_BUTTON)
                .addGap(64, 64, 64)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(jLabel6)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        PANE.addTab("DISPLAY LOAN", DISPLAYLOAN_PANE);

        jLabel7.setText("Enter loan number:");

        LOAN_NUMBER_FIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOAN_NUMBER_FIELDActionPerformed(evt);
            }
        });

        SEARCH_LOAN_TABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Loan Amount", "Term", "Loan Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SEARCH_LOAN_TABLE.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(SEARCH_LOAN_TABLE);
        if (SEARCH_LOAN_TABLE.getColumnModel().getColumnCount() > 0) {
            SEARCH_LOAN_TABLE.getColumnModel().getColumn(0).setResizable(false);
            SEARCH_LOAN_TABLE.getColumnModel().getColumn(1).setResizable(false);
            SEARCH_LOAN_TABLE.getColumnModel().getColumn(2).setResizable(false);
            SEARCH_LOAN_TABLE.getColumnModel().getColumn(3).setResizable(false);
        }

        SEARCH_LOAN_BACK_BUTTON.setText("Back");
        SEARCH_LOAN_BACK_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCH_LOAN_BACK_BUTTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SEARCHLOAN_PANELayout = new javax.swing.GroupLayout(SEARCHLOAN_PANE);
        SEARCHLOAN_PANE.setLayout(SEARCHLOAN_PANELayout);
        SEARCHLOAN_PANELayout.setHorizontalGroup(
            SEARCHLOAN_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SEARCHLOAN_PANELayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(SEARCHLOAN_PANELayout.createSequentialGroup()
                .addGroup(SEARCHLOAN_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SEARCHLOAN_PANELayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel7)
                        .addGap(26, 26, 26)
                        .addComponent(LOAN_NUMBER_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SEARCHLOAN_PANELayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SEARCH_LOAN_BACK_BUTTON)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SEARCHLOAN_PANELayout.setVerticalGroup(
            SEARCHLOAN_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SEARCHLOAN_PANELayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(SEARCH_LOAN_BACK_BUTTON)
                .addGap(26, 26, 26)
                .addGroup(SEARCHLOAN_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(LOAN_NUMBER_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        PANE.addTab("SEARCH LOAN", SEARCHLOAN_PANE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PANE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PANE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void APPLICANTNAME_FIELDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_APPLICANTNAME_FIELDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_APPLICANTNAME_FIELDKeyPressed

    private void LOANAMOUNT_FIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOANAMOUNT_FIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LOANAMOUNT_FIELDActionPerformed

    private void LOAN_APPLICATION_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOAN_APPLICATION_BUTTONActionPerformed
        // TODO add your handling code here:
         PANE.setSelectedComponent(LOANAPPLICATION_PANE);
    }//GEN-LAST:event_LOAN_APPLICATION_BUTTONActionPerformed

    private void LOAN_APPLICATION_BUTTONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOAN_APPLICATION_BUTTONMouseClicked
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_LOAN_APPLICATION_BUTTONMouseClicked

    private void LOAN_LIST_BUTTONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOAN_LIST_BUTTONMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_LOAN_LIST_BUTTONMouseClicked

    private void SEARCH_LOAN_BUTTONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SEARCH_LOAN_BUTTONMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SEARCH_LOAN_BUTTONMouseClicked

    private void LOAN_APPLICATION_BACK_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOAN_APPLICATION_BACK_BUTTONActionPerformed
        // TODO add your handling code here:
        PANE.setSelectedComponent(MAIN_PANE);
    }//GEN-LAST:event_LOAN_APPLICATION_BACK_BUTTONActionPerformed

    private void DISPLAY_LOAN_BACK_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DISPLAY_LOAN_BACK_BUTTONActionPerformed
        // TODO add your handling code here:
        PANE.setSelectedComponent(MAIN_PANE);
    }//GEN-LAST:event_DISPLAY_LOAN_BACK_BUTTONActionPerformed

    private void SEARCH_LOAN_BACK_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCH_LOAN_BACK_BUTTONActionPerformed
        // TODO add your handling code here:
        PANE.setSelectedComponent(MAIN_PANE);
    }//GEN-LAST:event_SEARCH_LOAN_BACK_BUTTONActionPerformed

    private void LOAN_LIST_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOAN_LIST_BUTTONActionPerformed
        // TODO add your handling code here:
        PANE.setSelectedComponent(DISPLAYLOAN_PANE);
    }//GEN-LAST:event_LOAN_LIST_BUTTONActionPerformed

    private void SEARCH_LOAN_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCH_LOAN_BUTTONActionPerformed
        // TODO add your handling code here:
        PANE.setSelectedComponent(SEARCHLOAN_PANE);
    }//GEN-LAST:event_SEARCH_LOAN_BUTTONActionPerformed

    private void APPLICANTNAME_FIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_APPLICANTNAME_FIELDActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_APPLICANTNAME_FIELDActionPerformed

    private void TERM_SELECTIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TERM_SELECTIONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TERM_SELECTIONActionPerformed

    private void LOAN_NUMBER_FIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOAN_NUMBER_FIELDActionPerformed
       
        // TODO add your handling code here:
    }//GEN-LAST:event_LOAN_NUMBER_FIELDActionPerformed

    private void SUBMIT_APPLICATION_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUBMIT_APPLICATION_BUTTONActionPerformed
       /* APPLICANTNAME_FIELD.getText();
         LOANAMOUNT_FIELD.getText(); */
       String choice =(String) TERM_SELECTION.getSelectedItem();
       String choice2 = (String) LOANTYPE_SELECTION.getSelectedItem();
       if(APPLICANTNAME_FIELD.getText().equals("")|| LOANAMOUNT_FIELD.getText().equals("") ||choice.equals("None")||choice2.equals("None")){
           JOptionPane.showMessageDialog(rootPane, "All fields must be filled.");
       }else{
           String obj = choice.toString();
           String obj2 = choice2.toString();
           String data[] = {APPLICANTNAME_FIELD.getText(),LOANAMOUNT_FIELD.getText(),obj,obj2};
           DefaultTableModel tblModel = (DefaultTableModel)DISPLAY_LOAN_TABLE.getModel();
           
           tblModel.insertRow(0,data);
           JOptionPane.showMessageDialog(rootPane, "Data saved successfully.");
       }
       
       
    }//GEN-LAST:event_SUBMIT_APPLICATION_BUTTONActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoansApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoansApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoansApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoansApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoansApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField APPLICANTNAME_FIELD;
    private javax.swing.JPanel DISPLAYLOAN_PANE;
    private javax.swing.JButton DISPLAY_LOAN_BACK_BUTTON;
    private javax.swing.JTable DISPLAY_LOAN_TABLE;
    private javax.swing.JTextField LOANAMOUNT_FIELD;
    private javax.swing.JPanel LOANAPPLICATION_PANE;
    private javax.swing.JComboBox<String> LOANTYPE_SELECTION;
    private javax.swing.JButton LOAN_APPLICATION_BACK_BUTTON;
    private javax.swing.JToggleButton LOAN_APPLICATION_BUTTON;
    private javax.swing.JToggleButton LOAN_LIST_BUTTON;
    private javax.swing.JTextField LOAN_NUMBER_FIELD;
    private javax.swing.JPanel MAIN_PANE;
    private javax.swing.JTabbedPane PANE;
    private javax.swing.JPanel SEARCHLOAN_PANE;
    private javax.swing.JButton SEARCH_LOAN_BACK_BUTTON;
    private javax.swing.JToggleButton SEARCH_LOAN_BUTTON;
    private javax.swing.JTable SEARCH_LOAN_TABLE;
    private javax.swing.JButton SUBMIT_APPLICATION_BUTTON;
    private javax.swing.JComboBox<String> TERM_SELECTION;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
