/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LoanPackage;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import javax.swing.table.TableRowSorter;
import javax.swing.RowSorter;
import javax.swing.RowFilter;
import java.util.ArrayList;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;




/**
 *
 * @author Louis Valencia
 */
public class LoansApplication extends javax.swing.JFrame {
 ArrayList<Loan> loans = new ArrayList<>();
    /**
     * Creates new form LoansApplication
     */
    public LoansApplication() {
        initComponents();
    }
       private int getTermValue(String term) {
        switch (term) {
            case "Short":
                return LoanConstants.shortTerm;
            case "Medium":
                return LoanConstants.mediumTerm;
            case "Long":
                return LoanConstants.longTerm;
            default:
                return 0; // Return 0 for unknown terms
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PANE = new javax.swing.JTabbedPane();
        MAIN_PANE = new javax.swing.JPanel();
        LOAN_APPLICATION_BUTTON = new javax.swing.JToggleButton();
        LOAN_LIST_BUTTON = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        primeInterestRateButton = new javax.swing.JButton();
        LOANAPPLICATION_PANE = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        APPLICANTNAME_FIELD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        LOANAMOUNT_FIELD = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TERM_SELECTION = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        LOANTYPE_SELECTION = new javax.swing.JComboBox<>();
        SUBMIT_APPLICATION_BUTTON = new javax.swing.JButton();
        LOAN_APPLICATION_BACK_BUTTON = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        LOANNUMBER_FIELD = new javax.swing.JTextField();
        DISPLAYLOAN_PANE = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DISPLAY_LOAN_TABLE = new javax.swing.JTable();
        DISPLAY_LOAN_BACK_BUTTON = new javax.swing.JButton();
        LOAN_NUMBER_FIELD1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        displayallbusinessloans = new javax.swing.JButton();
        displayallpersonalloans = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LOAN_APPLICATION_BUTTON.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        LOAN_APPLICATION_BUTTON.setText("LOAN APPLICATION");
        LOAN_APPLICATION_BUTTON.setBorderPainted(false);
        LOAN_APPLICATION_BUTTON.setFocusPainted(false);
        LOAN_APPLICATION_BUTTON.setRolloverEnabled(false);
        LOAN_APPLICATION_BUTTON.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOAN_APPLICATION_BUTTONMouseClicked(evt);
            }
        });
        LOAN_APPLICATION_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOAN_APPLICATION_BUTTONActionPerformed(evt);
            }
        });

        LOAN_LIST_BUTTON.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        LOAN_LIST_BUTTON.setText("LOAN LIST");
        LOAN_LIST_BUTTON.setBorderPainted(false);
        LOAN_LIST_BUTTON.setFocusPainted(false);
        LOAN_LIST_BUTTON.setRolloverEnabled(false);
        LOAN_LIST_BUTTON.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOAN_LIST_BUTTONMouseClicked(evt);
            }
        });
        LOAN_LIST_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOAN_LIST_BUTTONActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("KOMPANYA NI PERCY CO.");

        primeInterestRateButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        primeInterestRateButton.setText("Prime Interest Rate");
        primeInterestRateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeInterestRateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MAIN_PANELayout = new javax.swing.GroupLayout(MAIN_PANE);
        MAIN_PANE.setLayout(MAIN_PANELayout);
        MAIN_PANELayout.setHorizontalGroup(
            MAIN_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MAIN_PANELayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(MAIN_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(primeInterestRateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(MAIN_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(LOAN_APPLICATION_BUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LOAN_LIST_BUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(277, Short.MAX_VALUE))
        );
        MAIN_PANELayout.setVerticalGroup(
            MAIN_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MAIN_PANELayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(LOAN_APPLICATION_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LOAN_LIST_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(primeInterestRateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        PANE.addTab("MAIN", MAIN_PANE);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Applicant Name:");

        APPLICANTNAME_FIELD.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        APPLICANTNAME_FIELD.setToolTipText("");
        APPLICANTNAME_FIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                APPLICANTNAME_FIELDActionPerformed(evt);
            }
        });
        APPLICANTNAME_FIELD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                APPLICANTNAME_FIELDKeyPressed(evt);
            }
        });

        jLabel3.setText("Loan Amount:");

        LOANAMOUNT_FIELD.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        LOANAMOUNT_FIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOANAMOUNT_FIELDActionPerformed(evt);
            }
        });

        jLabel4.setText("Term:");

        TERM_SELECTION.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Short", "Medium", "Long", " " }));
        TERM_SELECTION.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TERM_SELECTION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TERM_SELECTIONActionPerformed(evt);
            }
        });

        jLabel5.setText("Loan Type:");

        LOANTYPE_SELECTION.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Business", "Personal" }));

        SUBMIT_APPLICATION_BUTTON.setText("Submit Application");
        SUBMIT_APPLICATION_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUBMIT_APPLICATION_BUTTONActionPerformed(evt);
            }
        });

        LOAN_APPLICATION_BACK_BUTTON.setText("Back");
        LOAN_APPLICATION_BACK_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOAN_APPLICATION_BACK_BUTTONActionPerformed(evt);
            }
        });

        jLabel8.setText("Loan Number:");

        LOANNUMBER_FIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOANNUMBER_FIELDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LOANAPPLICATION_PANELayout = new javax.swing.GroupLayout(LOANAPPLICATION_PANE);
        LOANAPPLICATION_PANE.setLayout(LOANAPPLICATION_PANELayout);
        LOANAPPLICATION_PANELayout.setHorizontalGroup(
            LOANAPPLICATION_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LOANAPPLICATION_PANELayout.createSequentialGroup()
                .addGroup(LOANAPPLICATION_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LOANAPPLICATION_PANELayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(LOANAPPLICATION_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LOANAPPLICATION_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addGap(32, 32, 32)
                        .addGroup(LOANAPPLICATION_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LOANTYPE_SELECTION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TERM_SELECTION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(APPLICANTNAME_FIELD, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(LOANAMOUNT_FIELD, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(LOANNUMBER_FIELD)))
                    .addGroup(LOANAPPLICATION_PANELayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LOAN_APPLICATION_BACK_BUTTON))
                    .addGroup(LOANAPPLICATION_PANELayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(SUBMIT_APPLICATION_BUTTON)))
                .addContainerGap(236, Short.MAX_VALUE))
        );
        LOANAPPLICATION_PANELayout.setVerticalGroup(
            LOANAPPLICATION_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LOANAPPLICATION_PANELayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(LOAN_APPLICATION_BACK_BUTTON)
                .addGap(22, 22, 22)
                .addGroup(LOANAPPLICATION_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(LOANNUMBER_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LOANAPPLICATION_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(APPLICANTNAME_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LOANAPPLICATION_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(LOANAMOUNT_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LOANAPPLICATION_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TERM_SELECTION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LOANAPPLICATION_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LOANTYPE_SELECTION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(SUBMIT_APPLICATION_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        TERM_SELECTION.getAccessibleContext().setAccessibleName("");

        PANE.addTab("LOAN APPLICATION", LOANAPPLICATION_PANE);

        DISPLAY_LOAN_TABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Loan #", "Name", "Loan Amount", "Term", "Loan type", "Amount Owed"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DISPLAY_LOAN_TABLE.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(DISPLAY_LOAN_TABLE);
        if (DISPLAY_LOAN_TABLE.getColumnModel().getColumnCount() > 0) {
            DISPLAY_LOAN_TABLE.getColumnModel().getColumn(0).setResizable(false);
            DISPLAY_LOAN_TABLE.getColumnModel().getColumn(1).setResizable(false);
            DISPLAY_LOAN_TABLE.getColumnModel().getColumn(2).setResizable(false);
            DISPLAY_LOAN_TABLE.getColumnModel().getColumn(3).setResizable(false);
            DISPLAY_LOAN_TABLE.getColumnModel().getColumn(4).setResizable(false);
            DISPLAY_LOAN_TABLE.getColumnModel().getColumn(5).setResizable(false);
        }

        DISPLAY_LOAN_BACK_BUTTON.setText("Back");
        DISPLAY_LOAN_BACK_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DISPLAY_LOAN_BACK_BUTTONActionPerformed(evt);
            }
        });

        LOAN_NUMBER_FIELD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOAN_NUMBER_FIELD1ActionPerformed(evt);
            }
        });
        LOAN_NUMBER_FIELD1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                LOAN_NUMBER_FIELD1KeyReleased(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("SEARCH");

        displayallbusinessloans.setText("Display Business Loans");
        displayallbusinessloans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                displayallbusinessloansMouseClicked(evt);
            }
        });
        displayallbusinessloans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayallbusinessloansActionPerformed(evt);
            }
        });

        displayallpersonalloans.setText("Display Personal Loans");
        displayallpersonalloans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayallpersonalloansActionPerformed(evt);
            }
        });

        jButton1.setText("Display all loans");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DISPLAYLOAN_PANELayout = new javax.swing.GroupLayout(DISPLAYLOAN_PANE);
        DISPLAYLOAN_PANE.setLayout(DISPLAYLOAN_PANELayout);
        DISPLAYLOAN_PANELayout.setHorizontalGroup(
            DISPLAYLOAN_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DISPLAYLOAN_PANELayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DISPLAYLOAN_PANELayout.createSequentialGroup()
                .addGroup(DISPLAYLOAN_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DISPLAYLOAN_PANELayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(DISPLAY_LOAN_BACK_BUTTON))
                    .addGroup(DISPLAYLOAN_PANELayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(displayallbusinessloans)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(DISPLAYLOAN_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(DISPLAYLOAN_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DISPLAYLOAN_PANELayout.createSequentialGroup()
                            .addComponent(LOAN_NUMBER_FIELD1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(249, 249, 249))
                        .addGroup(DISPLAYLOAN_PANELayout.createSequentialGroup()
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))
                    .addGroup(DISPLAYLOAN_PANELayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(displayallpersonalloans, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
        );
        DISPLAYLOAN_PANELayout.setVerticalGroup(
            DISPLAYLOAN_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DISPLAYLOAN_PANELayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(DISPLAYLOAN_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DISPLAY_LOAN_BACK_BUTTON)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LOAN_NUMBER_FIELD1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(DISPLAYLOAN_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(displayallbusinessloans)
                    .addComponent(displayallpersonalloans))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel6)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        PANE.addTab("DISPLAY LOAN", DISPLAYLOAN_PANE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PANE, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PANE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LOAN_NUMBER_FIELD1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LOAN_NUMBER_FIELD1KeyReleased
                                                   
    // TODO add your handling code here:
       // Get the loan number entered in the text field
       String loanNumberText = LOAN_NUMBER_FIELD1.getText();
    if (loanNumberText.isEmpty()) {
        // If the text field is empty, remove the row filter
        DISPLAY_LOAN_TABLE.setRowSorter(null);
        return;
    }
    
    int loanNumber = 0;
    try {
        loanNumber = Integer.parseInt(loanNumberText);
    } catch (NumberFormatException e) {
        // Handle non-integer input if needed
        return;
    }
    
    // Check if the table has a RowSorter, if not, create a new one
    if (DISPLAY_LOAN_TABLE.getRowSorter() == null) {
        DISPLAY_LOAN_TABLE.setRowSorter(new TableRowSorter<>(DISPLAY_LOAN_TABLE.getModel()));
    }
    
    // Get the TableRowSorter
    TableRowSorter<DefaultTableModel> sorter = (TableRowSorter<DefaultTableModel>) DISPLAY_LOAN_TABLE.getRowSorter();
    
    // Clear any existing row filter
    sorter.setRowFilter(null);
    
    // Create a row filter to match the loan number
    sorter.setRowFilter(RowFilter.regexFilter("^" + loanNumber + "$", 0));
    }//GEN-LAST:event_LOAN_NUMBER_FIELD1KeyReleased

    private void LOAN_NUMBER_FIELD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOAN_NUMBER_FIELD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LOAN_NUMBER_FIELD1ActionPerformed

    private void DISPLAY_LOAN_BACK_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DISPLAY_LOAN_BACK_BUTTONActionPerformed
        // TODO add your handling code here:
        PANE.setSelectedComponent(MAIN_PANE);
    }//GEN-LAST:event_DISPLAY_LOAN_BACK_BUTTONActionPerformed

    private void LOANNUMBER_FIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOANNUMBER_FIELDActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_LOANNUMBER_FIELDActionPerformed

    private void LOAN_APPLICATION_BACK_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOAN_APPLICATION_BACK_BUTTONActionPerformed
        // TODO add your handling code here:
        PANE.setSelectedComponent(MAIN_PANE);
    }//GEN-LAST:event_LOAN_APPLICATION_BACK_BUTTONActionPerformed

    private void SUBMIT_APPLICATION_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUBMIT_APPLICATION_BUTTONActionPerformed

       String choice = (String) TERM_SELECTION.getSelectedItem();
       String choice2 = (String) LOANTYPE_SELECTION.getSelectedItem();
       
         if(LOANNUMBER_FIELD.getText().equals("")||APPLICANTNAME_FIELD.getText().equals("")|| LOANAMOUNT_FIELD.getText().equals("") ||choice.equals("None")||choice2.equals("None")){
            JOptionPane.showMessageDialog(rootPane, "All fields must be filled.");
            
        }else if(choice2.equals("Personal")){
            //ARRAYLIST
        PersonalLoan ploan = new PersonalLoan();      //PERSONAL LOAN     
        ploan.setLoanNumber(Integer.parseInt(LOANNUMBER_FIELD.getText()));
        ploan.setCustomerLastName(APPLICANTNAME_FIELD.getText());
        ploan.setLoanAmt(Double.parseDouble(LOANAMOUNT_FIELD.getText()));
        String selectedTerm = (String) TERM_SELECTION.getSelectedItem();
    int term;
    switch (selectedTerm) {
    case "Short":
        term = LoanConstants.shortTerm;
        ploan.setTerm(term);
        break;
        
    case "Medium":
        term = LoanConstants.mediumTerm;
        ploan.setTerm(term);
        break;
        
    case "Long":
        term = LoanConstants.longTerm;
        ploan.setTerm(term);
        break;
        }
        loans.add(ploan);

        
        //TABLE
        PersonalLoan personalloan = new PersonalLoan(
                Integer.parseInt(LOANNUMBER_FIELD.getText()),
                APPLICANTNAME_FIELD.getText(),
                Double.parseDouble(LOANAMOUNT_FIELD.getText()),
                getTermValue(TERM_SELECTION.getSelectedItem().toString())
        );
        double amountOwed = personalloan.calculateOwed();
         String data[] = {
             LOANNUMBER_FIELD.getText(),
             APPLICANTNAME_FIELD.getText(),
             LOANAMOUNT_FIELD.getText(),
            // TERM_SELECTION.getSelectedItem().toString(),
            String.valueOf(getTermValue(TERM_SELECTION.getSelectedItem().toString())),
             choice2,String.valueOf(amountOwed)
         };
           /*Loan # , Name, LoanAmou/*Loan # , Name, nt , Term, Loan Type, Amount owed*/
         DefaultTableModel tblModel = (DefaultTableModel)DISPLAY_LOAN_TABLE.getModel();
            
           tblModel.insertRow(0,data);
            JOptionPane.showMessageDialog(rootPane, "Data saved successfully.");
            
            
        }else if(choice2.equals("Business")){
            //ARRAYLIST
            
            BusinessLoan bloan = new BusinessLoan();            //BUSINESS LOAN
        bloan.setLoanNumber(Integer.parseInt(LOANNUMBER_FIELD.getText()));
        bloan.setCustomerLastName(APPLICANTNAME_FIELD.getText());
        bloan.setLoanAmt(Double.parseDouble(LOANAMOUNT_FIELD.getText()));
        String selectedTerm = (String) TERM_SELECTION.getSelectedItem();
        int term;
        switch (selectedTerm) {
      case "Short":
        term = LoanConstants.shortTerm;
        bloan.setTerm(term);
        break;
        
        case "Medium":
        term = LoanConstants.mediumTerm;
        bloan.setTerm(term);
        break;
        
         case "Long":
        term = LoanConstants.longTerm;
        bloan.setTerm(term);
        break;
        }
    loans.add(bloan);

        
        // TABLE
        BusinessLoan businessloan = new BusinessLoan(Integer.parseInt(
                LOANNUMBER_FIELD.getText()),
                APPLICANTNAME_FIELD.getText(),
                Double.parseDouble(LOANAMOUNT_FIELD.getText()),
                getTermValue(TERM_SELECTION.getSelectedItem().toString())
        );
        double amountOwed = businessloan.calculateOwed();
         String data[] = {
             LOANNUMBER_FIELD.getText(),
             APPLICANTNAME_FIELD.getText(),
             LOANAMOUNT_FIELD.getText(),
             //TERM_SELECTION.getSelectedItem().toString(),
             String.valueOf(getTermValue(TERM_SELECTION.getSelectedItem().toString())),
             choice2,           
             String.valueOf(amountOwed)
         }; 
         /*Loan # , Name, loan amountnt , Term, Loan Type, Amount owed*/
         
            DefaultTableModel tblModel = (DefaultTableModel)DISPLAY_LOAN_TABLE.getModel();
            
           tblModel.insertRow(0,data);
            JOptionPane.showMessageDialog(rootPane, "Data saved successfully.");
        }
         
         
         
       //------------------------------------- 
//-----------------------------------------------
   

    }//GEN-LAST:event_SUBMIT_APPLICATION_BUTTONActionPerformed

    private void TERM_SELECTIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TERM_SELECTIONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TERM_SELECTIONActionPerformed

    private void LOANAMOUNT_FIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOANAMOUNT_FIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LOANAMOUNT_FIELDActionPerformed

    private void APPLICANTNAME_FIELDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_APPLICANTNAME_FIELDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_APPLICANTNAME_FIELDKeyPressed

    private void APPLICANTNAME_FIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_APPLICANTNAME_FIELDActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_APPLICANTNAME_FIELDActionPerformed

    private void LOAN_LIST_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOAN_LIST_BUTTONActionPerformed
        // TODO add your handling code here:
        PANE.setSelectedComponent(DISPLAYLOAN_PANE);
    }//GEN-LAST:event_LOAN_LIST_BUTTONActionPerformed

    private void LOAN_LIST_BUTTONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOAN_LIST_BUTTONMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_LOAN_LIST_BUTTONMouseClicked

    private void LOAN_APPLICATION_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOAN_APPLICATION_BUTTONActionPerformed
        // TODO add your handling code here:
        PANE.setSelectedComponent(LOANAPPLICATION_PANE);
    }//GEN-LAST:event_LOAN_APPLICATION_BUTTONActionPerformed

    private void LOAN_APPLICATION_BUTTONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOAN_APPLICATION_BUTTONMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_LOAN_APPLICATION_BUTTONMouseClicked

    private void displayallbusinessloansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayallbusinessloansActionPerformed
          DefaultTableModel model = (DefaultTableModel) DISPLAY_LOAN_TABLE.getModel();
    model.setRowCount(0); // Clear existing rows from the table
    
    for (Loan loan : loans) {
        if (loan instanceof BusinessLoan) {
            BusinessLoan businessLoan = (BusinessLoan) loan;
            String[] rowData = {
                String.valueOf(businessLoan.getLoanNumber()),
                businessLoan.getCustomerLastName(),
                String.valueOf(businessLoan.getLoanAmt()),
                String.valueOf(businessLoan.getTerm()),
                "Business", // Loan Type
                String.valueOf(businessLoan.calculateOwed())
            };
            model.addRow(rowData);
        }
    }
    displayallbusinessloans.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        // Call the method that handles the button click event
        displayallbusinessloansActionPerformed(evt);
    }
});
  
        
        // TODO add your handling code here:
    }//GEN-LAST:event_displayallbusinessloansActionPerformed

    private void displayallbusinessloansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displayallbusinessloansMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_displayallbusinessloansMouseClicked

    private void displayallpersonalloansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayallpersonalloansActionPerformed
            // TODO add your handling code here:
                  DefaultTableModel model = (DefaultTableModel) DISPLAY_LOAN_TABLE.getModel();
    model.setRowCount(0); // Clear existing rows from the table
    
    for (Loan loan : loans) {
        if (loan instanceof PersonalLoan) {
            PersonalLoan personalloan = (PersonalLoan) loan;
            String[] rowData = {
                String.valueOf(personalloan.getLoanNumber()),
                personalloan.getCustomerLastName(),
                String.valueOf(personalloan.getLoanAmt()),
                String.valueOf(personalloan.getTerm()),
                "Personal", // Loan Type
                String.valueOf(personalloan.calculateOwed())
            };
            model.addRow(rowData);
        }
        
    }
     displayallpersonalloans.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        // Call the method that handles the button click event
        displayallpersonalloansActionPerformed(evt);
    }
     });
             
    }//GEN-LAST:event_displayallpersonalloansActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        displayAllLoans();
    }//GEN-LAST:event_jButton1ActionPerformed
        private boolean primeRateEntered = false;
    private void primeInterestRateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeInterestRateButtonActionPerformed
        // TODO add your handling code here:
         if (primeRateEntered) {
        // If already entered, show a message indicating that it cannot be clicked again
        JOptionPane.showMessageDialog(this, "Prime interest rate already entered.");
        return;
    }
    
    // Prompt the user to enter the prime interest rate
    String primeRateStr = JOptionPane.showInputDialog(this, "Enter the prime interest rate:");
    
    // Validate the input and store the prime interest rate
    if (primeRateStr != null && !primeRateStr.isEmpty()) {
        try {
            double primeRate = Double.parseDouble(primeRateStr);
            // Store the prime interest rate and set the flag to true
            LoanConstants.setInterestRate(primeRate);
            primeRateEntered = true;
            
            // Disable the button
            primeInterestRateButton.setEnabled(false);
        } catch (NumberFormatException e) {
            // Handle invalid input if needed
            JOptionPane.showMessageDialog(this, "Invalid input. Please enter a valid number.");
        }
    } else {
        // Handle cancel or empty input
        JOptionPane.showMessageDialog(this, "Prime interest rate input cancelled or empty.");
    }
    }//GEN-LAST:event_primeInterestRateButtonActionPerformed
    private void displayAllLoans() {
    jButton1.addActionListener(new ActionListener() {
        
        @Override
        public void actionPerformed(ActionEvent e) {
            DefaultTableModel model = (DefaultTableModel) DISPLAY_LOAN_TABLE.getModel();
            model.setRowCount(0); // Clear existing rows from the table

            // Iterate through the list of loans and add each loan to the table
            for (Loan loan : loans) {
                String[] rowData = {
                    String.valueOf(loan.getLoanNumber()),
                    loan.getCustomerLastName(),
                    String.valueOf(loan.getLoanAmt()),
                    String.valueOf(loan.getTerm()),
                    loan instanceof PersonalLoan ? "Personal" : "Business", // Determine loan type
                    String.valueOf(loan.calculateOwed())
                };
                model.addRow(rowData); // Add the row to the table
            }
        }
    });
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoansApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoansApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoansApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoansApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoansApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField APPLICANTNAME_FIELD;
    private javax.swing.JPanel DISPLAYLOAN_PANE;
    private javax.swing.JButton DISPLAY_LOAN_BACK_BUTTON;
    private javax.swing.JTable DISPLAY_LOAN_TABLE;
    private javax.swing.JTextField LOANAMOUNT_FIELD;
    private javax.swing.JPanel LOANAPPLICATION_PANE;
    private javax.swing.JTextField LOANNUMBER_FIELD;
    private javax.swing.JComboBox<String> LOANTYPE_SELECTION;
    private javax.swing.JButton LOAN_APPLICATION_BACK_BUTTON;
    private javax.swing.JToggleButton LOAN_APPLICATION_BUTTON;
    private javax.swing.JToggleButton LOAN_LIST_BUTTON;
    private javax.swing.JTextField LOAN_NUMBER_FIELD1;
    private javax.swing.JPanel MAIN_PANE;
    private javax.swing.JTabbedPane PANE;
    private javax.swing.JButton SUBMIT_APPLICATION_BUTTON;
    private javax.swing.JComboBox<String> TERM_SELECTION;
    private javax.swing.JButton displayallbusinessloans;
    private javax.swing.JButton displayallpersonalloans;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton primeInterestRateButton;
    // End of variables declaration//GEN-END:variables
}
